#!/usr/bin/env python3
"""Generate Astro content-collection entries from the catalogs in public/papers/.

Inputs
  public/papers/papers.md                 -> src/content/publications/<stem>.md
  public/papers/github_projects.md        -> src/content/software/<slug>.md
  public/papers/github_repos_inventory.csv (stars/last-push fallback)

Usage
  python3 scripts/generate_content.py        # regenerate everything
  python3 scripts/generate_content.py --dry  # report only

Edit the catalogs (or the mapping tables below), rerun, commit. Generated
files carry a header comment; any file without that header is treated as
hand-edited and left untouched.
"""
from __future__ import annotations

import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAPERS_MD = ROOT / "public/papers/papers.md"
GITHUB_MD = ROOT / "public/papers/github_projects.md"
INVENTORY = ROOT / "public/papers/github_repos_inventory.csv"
PUB_DIR = ROOT / "src/content/publications"
SW_DIR = ROOT / "src/content/software"
GENERATED = "<!-- generated by scripts/generate_content.py; edit the catalog instead -->"

TOPICS = {
    "agents": "AI agents & workflows",
    "assistants": "AI assistants & evaluation",
    "thermo": "Thermochemistry & kinetics",
    "mlp": "ML potentials & 2D materials",
    "solvers": "Eigensolvers & scientific software",
    "vib": "Vibrational & electronic structure theory",
    "materials": "Materials & catalysis",
    "education": "Education & outreach",
    "bec": "Ultracold atoms",
}

# stem: (project slug, topic key, featured, type)
PAPER_MAP = {
    "2026_pham_chemgraph": ("chemgraph-agents", "agents", True, "journal"),
    "2026_pham_multiagent_materials_screening": ("chemgraph-agents", "agents", True, "preprint"),
    "2026_grizzi_chemgraph_xanes": ("chemgraph-agents", "agents", False, "preprint"),
    "2026_tummalapalli_ensemblelauncher": ("chemgraph-agents", "agents", False, "preprint"),
    "2026_smith_petsc_agent_workflows": ("ai-assistants-hpc", "assistants", False, "report"),
    "2026_roy_llm_hackathon_materials_chemistry": ("chemgraph-agents", "agents", False, "preprint"),
    "2025_kocabas_mos2_mose2_thermal_conductivity": ("ml-potentials-2d-materials", "mlp", True, "journal"),
    "2025_cappello_eaira": ("ai-assistants-hpc", "assistants", True, "preprint"),
    "2025_smith_petsc_ai_assistants": ("ai-assistants-hpc", "assistants", False, "preprint"),
    "2025_bondapalli_askhpc": ("ai-assistants-hpc", "assistants", True, "conference"),
    "2025_reji_zr_mof_co2_photoreduction": (None, "materials", False, "journal"),
    "2025_wen_red_teaming_generative_ai_copyright": ("ai-assistants-hpc", "assistants", False, "report"),
    "2024_leung_intro_hpc_bootcamp": ("education-outreach", "education", False, "journal"),
    "2023_elliott_cbh_anl_heats_of_formation": ("automated-thermochemistry", "thermo", True, "journal"),
    "2023_elliott_alkane_oxidation_thermodynamics": ("automated-thermochemistry", "thermo", False, "journal"),
    "2023_kocabas_gap_2d_thermal_properties": ("ml-potentials-2d-materials", "mlp", True, "journal"),
    "2023_kocabas_gap_2d_thermal_properties_si": ("ml-potentials-2d-materials", "mlp", False, "supplement"),
    "2023_richard_pluginplay": ("eigensolvers-exascale-software", "solvers", False, "journal"),
    "2021_kowalski_nwchem_to_nwchemex": ("eigensolvers-exascale-software", "solvers", False, "review"),
    "2021_demiroglu_graphene_thermal_expansion_gap": ("ml-potentials-2d-materials", "mlp", False, "journal"),
    "2021_elliott_automech_pyrolysis_kinetics": ("automated-thermochemistry", "thermo", True, "journal"),
    "2021_ruiz_co2_trimer_anharmonic": ("anharmonic-vibrations", "vib", False, "journal"),
    "2020_yu_elsi": ("eigensolvers-exascale-software", "solvers", False, "journal"),
    "2019_keceli_butane_thermochemistry": ("automated-thermochemistry", "thermo", True, "journal"),
    "2019_fletcher_valence_vsvb": ("eigensolvers-exascale-software", "solvers", False, "journal"),
    "2019_maystrovsky_co2_dimer_anharmonic": ("anharmonic-vibrations", "vib", False, "journal"),
    "2018_keceli_siesta_sips": ("eigensolvers-exascale-software", "solvers", True, "journal"),
    "2018_sarikurt_mxene_thermal_thermoelectric": ("ml-potentials-2d-materials", "mlp", False, "journal"),
    "2016_keceli_sips_eigensolver_dftb": ("eigensolvers-exascale-software", "solvers", True, "journal"),
    "2012_hirata_extensivity_crystals": ("anharmonic-vibrations", "vib", False, "review"),
    "2010_keceli_fast_ccsd_extended_systems": ("anharmonic-vibrations", "vib", True, "journal"),
    "2010_hirata_anharmonic_lattice_vibrations": ("anharmonic-vibrations", "vib", False, "journal"),
    "2009_keceli_anharmonic_combustion_species": ("anharmonic-vibrations", "vib", False, "journal"),
    "2009_sode_solid_hf_coupled_cluster": ("anharmonic-vibrations", "vib", False, "journal"),
    "2007_keceli_nonlinear_optics_ansatz_bec": (None, "bec", False, "journal"),
    "2006_keceli_tkachenko_modes_two_component_bec": (None, "bec", False, "journal"),
}

PAPER_CODE = {
    "2026_pham_chemgraph": "https://github.com/argonne-lcf/ChemGraph",
    "2026_grizzi_chemgraph_xanes": "https://github.com/argonne-lcf/ChemGraph",
    "2023_kocabas_gap_2d_thermal_properties": "https://github.com/AI4Materials/2DM-GAP",
    "2023_kocabas_gap_2d_thermal_properties_si": "https://github.com/AI4Materials/2DM-GAP",
    "2019_keceli_butane_thermochemistry": "https://github.com/PACChem/QTC",
    "2021_elliott_automech_pyrolysis_kinetics": "https://github.com/Auto-Mech",
    "2023_richard_pluginplay": "https://github.com/NWChemEx/PluginPlay",
    "2019_fletcher_valence_vsvb": "https://github.com/VALENCE-software/VALENCE",
    "2016_keceli_sips_eigensolver_dftb": "https://github.com/keceli/SLEPc-SIPs",
    "2018_keceli_siesta_sips": "https://github.com/keceli/siesta-sips",
    "2020_yu_elsi": "https://github.com/ElectronicStructureLibrary/elsi-interface",
    "2025_bondapalli_askhpc": "https://github.com/argonne-lcf/HPCBot",
    "2025_smith_petsc_ai_assistants": "https://github.com/petsc/petscagent-bench",
    "2026_smith_petsc_agent_workflows": "https://github.com/petsc/petscagent-bench",
    "2024_leung_intro_hpc_bootcamp": "https://github.com/keceli/IntroductionToHPCBootcamp",
}

AREAS = {"ai": "AI", "hpc": "HPC", "quantum": "Quantum Chemistry"}

# default research areas by topic key; per-paper overrides below
TOPIC_AREAS = {
    "agents": ["ai", "hpc", "quantum"],
    "assistants": ["ai", "hpc"],
    "thermo": ["quantum", "hpc"],
    "mlp": ["ai", "quantum"],
    "solvers": ["hpc", "quantum"],
    "vib": ["quantum"],
    "materials": ["quantum"],
    "education": ["hpc"],
    "bec": ["quantum"],
}
PAPER_AREAS = {
    "2026_tummalapalli_ensemblelauncher": ["hpc", "ai"],
    "2026_roy_llm_hackathon_materials_chemistry": ["ai", "quantum"],
    "2025_wen_red_teaming_generative_ai_copyright": ["ai"],
    "2025_cappello_eaira": ["ai"],
    "2018_sarikurt_mxene_thermal_thermoelectric": ["quantum"],
    "2010_keceli_fast_ccsd_extended_systems": ["quantum", "hpc"],
    "2024_leung_intro_hpc_bootcamp": ["hpc", "ai"],
}
THEME_AREAS = {
    "1": ["ai", "quantum"],
    "2": ["quantum", "hpc"],
    "3": ["quantum", "hpc"],
    "4": ["ai", "quantum"],
    "5": ["hpc", "quantum"],
    "6": ["ai", "hpc"],
    "7": ["hpc"],
    "8": ["hpc", "ai"],
    "9": ["ai", "hpc"],
}

THEME_PROJECT = {
    "1": "chemgraph-agents",
    "2": "chemgraph-agents",
    "3": "automated-thermochemistry",
    "4": "ml-potentials-2d-materials",
    "5": "eigensolvers-exascale-software",
    "6": "ai-assistants-hpc",
    "7": "ai-assistants-hpc",
    "8": "education-outreach",
}

SOFTWARE_FEATURED = {
    "argonne-lcf/ChemGraph",
    "Autonomous-Scientific-Agents/IQC",
    "Autonomous-Scientific-Agents/HashMol3D",
    "PACChem/QTC",
    "AI4Materials/2DM-GAP",
    "keceli/SLEPc-SIPs",
    "NWChemEx/PluginPlay",
    "argonne-lcf/HPCBot",
    "Autonomous-Scientific-Agents/IQC-Dashboard",
    "petsc/petscagent-bench",
}

SOFTWARE_SKIP_THEMES = {"10"}  # personal utilities and website

ARXIV_RE = re.compile(r"arXiv:(\d{4}\.\d{4,5})")
DOI_RE = re.compile(r"doi:\s*(10\.\S+)")


def yaml_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def yaml_list(items):
    if not items:
        return "[]"
    return "\n" + "\n".join(f"  - {yaml_str(i)}" for i in items)


def parse_papers():
    text = PAPERS_MD.read_text(encoding="utf-8")
    blocks = re.split(r"^### `", text, flags=re.M)[1:]
    entries = []
    for b in blocks:
        stem_line, _, body = b.partition("\n")
        stem = stem_line.split("`")[0].replace(".pdf", "")
        fields = {}
        for m in re.finditer(r"^- \*\*(.+?):\*\* (.+)$", body, flags=re.M):
            fields[m.group(1).strip().lower()] = m.group(2).strip()
        entries.append((stem, fields))
    return entries


def role_from(text: str) -> str:
    t = text.lower()
    if t.startswith("first"):
        return "first"
    if "corresponding" in t:
        return "corresponding"
    return "coauthor"


def split_authors(s: str):
    s = re.sub(r"\s*\(.*?\)", "", s)
    s = s.replace("; corresponding author", ", corresponding author")
    parts = [a.strip() for a in re.split(r",\s*|;\s*", s) if a.strip()]
    return [p for p in parts if p not in {"et al.", "..."}]


def is_generated(p: Path) -> bool:
    return GENERATED in p.read_text(encoding="utf-8")


def write_publications(dry: bool):
    PUB_DIR.mkdir(parents=True, exist_ok=True)
    written = 0
    for stem, f in parse_papers():
        if stem not in PAPER_MAP:
            print(f"  ! no mapping for {stem}; skipped", file=sys.stderr)
            continue
        project, topic_key, featured, ptype = PAPER_MAP[stem]
        year = int(stem[:4])
        venue = f.get("venue", "")
        doi = DOI_RE.search(venue)
        arxiv = ARXIV_RE.search(venue)
        keywords = [k.strip() for k in f.get("keywords", "").split(",") if k.strip()]
        venue_clean = re.sub(r",?\s*doi:\s*10\.\S+", "", venue).strip()
        fm = [
            "---",
            f"title: {yaml_str(f['title'])}",
            f"authors: {yaml_list(split_authors(f['authors']))}",
            f"venue: {yaml_str(venue_clean)}",
            f"year: {year}",
            f"date: {year}-01-01",
            f"type: {ptype}",
        ]
        if doi:
            fm.append(f"doi: {yaml_str(doi.group(1).rstrip(','))}")
        if arxiv:
            fm.append(f"arxiv: {yaml_str(arxiv.group(1))}")
        fm.append(f"pdf: {yaml_str('/papers/' + stem + '.pdf')}")
        if stem in PAPER_CODE:
            fm.append(f"code: {yaml_str(PAPER_CODE[stem])}")
        if project:
            fm.append(f"project: {yaml_str(project)}")
        fm.append(f"topic: {yaml_str(TOPICS[topic_key])}")
        fm.append(f"areas: {yaml_list(PAPER_AREAS.get(stem, TOPIC_AREAS[topic_key]))}")
        fm.append(f"keywords: {yaml_list(keywords)}")
        fm.append(f"featured: {'true' if featured else 'false'}")
        fm.append(f"summary: {yaml_str(f['summary'])}")
        fm.append("---")
        fm += [GENERATED, "", f["summary"], ""]
        out = PUB_DIR / f"{stem}.md"
        if out.exists() and not is_generated(out):
            print(f"  ~ {out.name} is hand-edited; left untouched")
            continue
        if not dry:
            out.write_text("\n".join(fm), encoding="utf-8")
        written += 1
    print(f"publications: {written} entries")


SW_LINE = re.compile(
    r"^- \*\*\[(?P<name>[^\]]+)\]\((?P<url>[^)]+)\)\*\* · (?P<lang>[^·\n]+) · ★(?P<stars>\d+) · (?P<years>[^·\n]+)"
    r"(?: · ~(?P<commits>\d+) commits by keceli)?(?: · (?P<role>[^\n]+))?\n"
    r"  (?P<note>.+)\n  \*Keywords:\* (?P<kw>.+)$",
    re.M,
)


def load_inventory():
    inv = {}
    if INVENTORY.exists():
        with INVENTORY.open(encoding="utf-8") as fh:
            for row in csv.DictReader(fh):
                inv[row["full_name"]] = row
    return inv


def write_software(dry: bool):
    SW_DIR.mkdir(parents=True, exist_ok=True)
    text = GITHUB_MD.read_text(encoding="utf-8")
    inv = load_inventory()
    written = 0
    seen_slugs: set[str] = set()
    sections = re.split(r"^## (\d+)\. (.+)$", text, flags=re.M)
    for i in range(1, len(sections), 3):
        num, theme, body = sections[i], sections[i + 1].strip(), sections[i + 2]
        if num in SOFTWARE_SKIP_THEMES:
            continue
        for m in SW_LINE.finditer(body):
            full = m.group("name")
            slug = full.split("/")[-1].lower()
            if slug in seen_slugs:
                slug = full.replace("/", "-").lower()
            seen_slugs.add(slug)
            lang = m.group("lang").strip()
            lang = None if lang in {"—", "None"} else lang
            row = inv.get(full, {})
            stars = int(m.group("stars") or row.get("stars") or 0)
            last_push = row.get("last_push", "")
            status = "active" if last_push >= "2025-09" else ("maintained" if last_push >= "2023-01" else "archived")
            keywords = [k.strip() for k in m.group("kw").split(",") if k.strip()]
            fm = [
                "---",
                f"title: {yaml_str(full.split('/')[-1])}",
                f"fullName: {yaml_str(full)}",
                f"summary: {yaml_str(m.group('note').strip())}",
                f"repo: {yaml_str(m.group('url'))}",
            ]
            if lang:
                fm.append(f"language: {yaml_str(lang)}")
            fm.append(f"stars: {stars}")
            fm.append(f"years: {yaml_str(m.group('years').strip())}")
            if m.group("commits"):
                fm.append(f"commits: {m.group('commits')}")
            if m.group("role"):
                fm.append(f"role: {yaml_str(m.group('role').strip())}")
            fm.append(f"theme: {yaml_str(theme)}")
            fm.append(f"areas: {yaml_list(THEME_AREAS.get(num, []))}")
            if num in THEME_PROJECT:
                fm.append(f"project: {yaml_str(THEME_PROJECT[num])}")
            fm.append(f"keywords: {yaml_list(keywords)}")
            fm.append(f"featured: {'true' if full in SOFTWARE_FEATURED else 'false'}")
            fm.append(f"status: {status}")
            fm.append("---")
            fm += [GENERATED, "", m.group("note").strip(), ""]
            out = SW_DIR / f"{slug}.md"
            if out.exists() and not is_generated(out):
                print(f"  ~ {out.name} is hand-edited; left untouched")
                continue
            if not dry:
                out.write_text("\n".join(fm), encoding="utf-8")
            written += 1
    print(f"software: {written} entries")


def main():
    dry = "--dry" in sys.argv
    if not dry:
        for d in (PUB_DIR, SW_DIR):
            if d.exists():
                for p in d.glob("*.md"):
                    if is_generated(p):
                        p.unlink()
    write_publications(dry)
    write_software(dry)


if __name__ == "__main__":
    main()
